// <auto-generated />
using System;
using Datos.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Datos.Migrations
{
    [DbContext(typeof(D_ContextDB))]
    partial class D_ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades.Modelos.PlanesDeEstudio.Carreras.E_Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<string>("AliasCarrera")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("Relational:Name", "UK_AliasCarrera");

                    b.Property<string>("ClaveCarrera")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(3)")
                        .HasAnnotation("Relational:Name", "UK_ClaveCarrera");

                    b.Property<bool>("EstadoCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreCarrera")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("Relational:Name", "UK_NombreCarrera");

                    b.HasKey("IdCarrera");

                    b.ToTable("Carreras", "CEF");
                });

            modelBuilder.Entity("Entidades.Modelos.PlanesDeEstudio.Carreras.E_PlanEstudio", b =>
                {
                    b.Property<int>("IdPlanEstudio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanEstudio"));

                    b.Property<string>("CampoOcupacional")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("CarreraIdCarrera")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("CreditosObligatorios")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("CreditosOptativos")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<bool>("EstadoPlanEstudio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int");

                    b.Property<int>("IdNivelAcademico")
                        .HasColumnType("int");

                    b.Property<string>("PerfelDeEgreso")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PerfilDeIngreso")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PlanEstudio")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(6)")
                        .HasAnnotation("Relational:Name", "UK_PlanEstudio");

                    b.Property<int>("TotalCreditos")
                        .HasColumnType("int");

                    b.HasKey("IdPlanEstudio");

                    b.HasIndex("CarreraIdCarrera");

                    b.ToTable("PlanesEstudio", "CEF");
                });

            modelBuilder.Entity("Entidades.Modelos.PlanesDeEstudio.Carreras.E_PlanEstudio", b =>
                {
                    b.HasOne("Entidades.Modelos.PlanesDeEstudio.Carreras.E_Carrera", "Carrera")
                        .WithMany("PlanEstudios")
                        .HasForeignKey("CarreraIdCarrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("Entidades.Modelos.PlanesDeEstudio.Carreras.E_Carrera", b =>
                {
                    b.Navigation("PlanEstudios");
                });
#pragma warning restore 612, 618
        }
    }
}
